name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]
jobs:
  build:
    name: Build and Test
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'pomadchin/db-sample'
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [21]
        distribution: [temurin]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Check formatting
        run: sbt scalafmtCheckAll

      - name: Build project
        run: sbt test

